// data.h — input test vectors as const arrays (generated by ../tools/embed_data.py).
// Do not edit by hand: regenerate with `python3 ../tools/embed_data.py ..` after
// re-running the dump tools. Values are the exact %.3e decimals from data/*.txt.
#pragma once

#include <cstdint>

// kX: (64,) — two groups of 32 floats, exercises per-group scales  [64 values, mirror of data/input_x.txt]
inline const float kX[] = {
    -1.250e-01f, -1.875e-01f, -1.875e-01f, -1.250e-01f, 0.000e+00f, 3.125e-02f, 1.250e-01f, 2.812e-01f, 5.000e-01f, -6.250e-01f, -9.375e-02f, -1.250e-01f, -9.375e-02f, 0.000e+00f, 1.562e-01f, 6.250e-02f, 1.875e-01f, 3.750e-01f, -5.000e-01f, -4.688e-01f, -6.250e-02f, -6.250e-02f, 0.000e+00f, 1.250e-01f, 3.125e-01f, 9.375e-02f, 2.500e-01f, -3.750e-01f, -3.750e-01f, -3.125e-01f, -3.125e-02f, 0.000e+00f, 9.375e-02f, 2.500e-01f, 4.688e-01f, 1.250e-01f, -2.500e-01f, -2.812e-01f, -2.500e-01f, -1.562e-01f, 0.000e+00f, 6.250e-02f, 1.875e-01f, 3.750e-01f, 6.250e-01f, -1.250e-01f, -1.875e-01f, -1.875e-01f, -1.250e-01f, 0.000e+00f, 3.125e-02f, 1.250e-01f, 2.812e-01f, 5.000e-01f, -6.250e-01f, -9.375e-02f, -1.250e-01f, -9.375e-02f, 0.000e+00f, 1.562e-01f, 6.250e-02f, 1.875e-01f, 3.750e-01f, -5.000e-01f
};

// kMatmulXQ: (n,) = (8,) — quantized x values (toy fixture: GS=4)  [8 values, mirror of data/input_matmul_xq.txt]
inline const int8_t kMatmulXQ[] = {
    4, -3, 2, 6, -5, 1, 0, -2
};

// kMatmulXS: (n/GS,) = (2,) — per-group scales of x  [2 values, mirror of data/input_matmul_xs.txt]
inline const float kMatmulXS[] = {
    1.000e-01f, 2.000e-01f
};

// kMatmulWQ: (d, n) = (3, 8), row-major — quantized weight values  [24 values, mirror of data/input_matmul_wq.txt]
inline const int8_t kMatmulWQ[] = {
    3, -2, 5, 1, -4, 6, -1, 2, 0, 7, -3, -5, 1, 1, -2, 4, 2, -6, 3, 0, -1, 5, -7, 2
};

// kMatmulWS: (d, n/GS) = (3, 2), row-major — per-group scales of w  [6 values, mirror of data/input_matmul_ws.txt]
inline const float kMatmulWS[] = {
    2.000e-02f, 5.000e-02f, 1.000e-02f, 3.000e-02f, 4.000e-02f, 2.000e-02f
};

