#!/usr/bin/env python3
"""Generate per-module data.h files: input test vectors as namespace-scope
const arrays, so module code can focus on the inference algorithms instead
of file parsing.

Each entry below maps a data/input_*.txt file (produced by dump_fp32.cpp /
dump_int8.cpp) to a const array. The decimal literals are the exact %.3e
values from the txt files, so the embedded data is bit-identical to what
read_floats() would produce.

usage: python3 embed_data.py <tutorial_root>   e.g. python3 embed_data.py inference_tutorial
Regenerate after re-running the dump tools.
"""

import os
import sys

# (module, txt file, C++ type, array name, shape comment)
ARRAYS = [
    # 03_rmsnorm_softmax: real 288-dim case (toy 8-dim vectors stay inline in main.cpp)
    ("03_rmsnorm_softmax", "input_rmsnorm_x_real.txt", "float", "kRmsNormXReal",
     "(dim,) — embedding row of the first prompt token (id 1 = <s>)"),
    ("03_rmsnorm_softmax", "input_rmsnorm_w_real.txt", "float", "kRmsNormWReal",
     "(dim,) — layer-0 slice of rms_att_weight"),

    # 05_rope: q/k of all P=5 prompt positions, layer 0, before RoPE (pos-major)
    ("05_rope", "input_q.txt", "float", "kQ",
     "(P, dim) = (5, 288), pos-major — q projections before RoPE"),
    ("05_rope", "input_k.txt", "float", "kK",
     "(P, kv_dim) = (5, 288), pos-major — k projections before RoPE"),

    # 06_attention: q/k/v of all P=5 prompt positions, layer 0, after RoPE (pos-major)
    ("06_attention", "input_q.txt", "float", "kQ",
     "(P, dim) = (5, 288), pos-major — q after RoPE"),
    ("06_attention", "input_k_cache.txt", "float", "kKCache",
     "(P, kv_dim) = (5, 288), pos-major — key cache content after RoPE"),
    ("06_attention", "input_v_cache.txt", "float", "kVCache",
     "(P, kv_dim) = (5, 288), pos-major — value cache content"),

    # 07_ffn: FFN input at the last prompt position, layer 0 (after rms_ffn_weight)
    ("07_ffn", "input_x.txt", "float", "kX",
     "(dim,) = (288,) — FFN input at the last prompt position"),

    # 12_quantize: small quantization kernel cases
    ("12_quantize", "input_x.txt", "float", "kX",
     "(64,) — two groups of 32 floats, exercises per-group scales"),
    ("12_quantize", "input_matmul_xq.txt", "int8_t", "kMatmulXQ",
     "(n,) = (8,) — quantized x values (toy fixture: GS=4)"),
    ("12_quantize", "input_matmul_xs.txt", "float", "kMatmulXS",
     "(n/GS,) = (2,) — per-group scales of x"),
    ("12_quantize", "input_matmul_wq.txt", "int8_t", "kMatmulWQ",
     "(d, n) = (3, 8), row-major — quantized weight values"),
    ("12_quantize", "input_matmul_ws.txt", "float", "kMatmulWS",
     "(d, n/GS) = (3, 2), row-major — per-group scales of w"),
]

HEADER = """// data.h — input test vectors as const arrays (generated by ../tools/embed_data.py).
// Do not edit by hand: regenerate with `python3 ../tools/embed_data.py ..` after
// re-running the dump tools. Values are the exact %.3e decimals from data/*.txt.
#pragma once

#include <cstdint>

"""


def read_values(path):
    with open(path) as f:
        return f.read().split()


def format_float(tok):
    # txt holds %.3e decimals; re-emit as a float literal with the same text
    return f"{float(tok):.3e}f"


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    per_module = {}
    for module, txt, ctype, name, comment in ARRAYS:
        per_module.setdefault(module, []).append((txt, ctype, name, comment))

    for module, arrays in sorted(per_module.items()):
        out = [HEADER]
        for txt, ctype, name, comment in arrays:
            path = os.path.join(root, module, "data", txt)
            values = read_values(path)
            if ctype == "float":
                body = ", ".join(format_float(t) for t in values)
            else:
                body = ", ".join(str(int(t)) for t in values)
            out.append(f"// {name}: {comment}  [{len(values)} values, mirror of data/{txt}]\n")
            out.append(f"inline const {ctype} {name}[] = {{\n    {body}\n}};\n\n")
        dest = os.path.join(root, module, "data.h")
        with open(dest, "w") as f:
            f.write("".join(out))
        print(f"wrote {dest}")


if __name__ == "__main__":
    main()
